### ISSUE TITLE
yoda-route53 publish job keeps restarting in coreos cluster

### ISSUE THREAD

**Issue by sukrit007** [totem/yoda-discover#1]
**Description**:
The job keeps restarting with error:
etcd.EtcdException: Unable to decode server response: Expecting value: line 1 column 1 (char 0)

**Full trace**:
etcd.EtcdException: Unable to decode server response: Expecting value: line 1 column 1 (char 0)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: 'Unable to decode server response: %s' % e)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/local/lib/python3.4/dist-packages/etcd/client.py", line 527, in _result_from_response
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: return self._result_from_response(response)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/local/lib/python3.4/dist-packages/etcd/client.py", line 345, in read
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: result = etcd_cl.read(**etcd_args)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/opt/yoda-discover/discover/yoda_route53/__main__.py", line 155, in route53_sync
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: route53_sync(parsed_args)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/opt/yoda-discover/discover/yoda_route53/**main**.py", line 258, in <module>
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: exec(code, run_globals)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: "__main__", mod_spec)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: Traceback (most recent call last):
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: During handling of the above exception, another exception occurred:
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: ValueError: Expecting value: line 1 column 1 (char 0)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: raise ValueError(errmsg("Expecting value", s, err.value)) from None
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: return _default_decoder.decode(s)
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: res = json.loads(response.data.decode('utf-8'))
Jan 02 03:34:53 ip-10-232-8-60.us-west-1.compute.internal sh[21769]: File "/usr/local/lib/python3.4/dist-packages/etcd/client.py", line 519, in _result_from_response

**Comment by sukrit007** [comment]
Fixed
